### ISSUE TITLE
Add support for deadletters

### ISSUE THREAD

**Issue by leandro-lugaresi** [leandro-lugaresi/message-cannon#17]
Deadletters are a nice way to implement a lot of things in rabbitMQ and today we have the possibility to add the arguments in queue configs but the deadletter exchange or queue may not exist.
To prevent this to happen we will declare all the deadletters on consumer's factory.

The config will be like this:
```yml
rabbitmq:
  connections:
    default:
      dsn: "amqp://localhost:5672"
      timeout: 1s
      sleep: 500ms
  exchanges:
    upload-picture:
      type: topic
      options:
        no_wait: false
    fallback:
      type: topic
  dead_letters:
    fallback:
      queue:
        name: "fallback"
        options:
          durable: true
          args:
            "x-dead-letter-exchange": ""
            "x-message-ttl": 300000
        bindings:
          -
            routing_keys: ["#"]
            exchange: fallback
  consumers:
    test1:
      connection: default
      workers: 1                           # Workers count. Defaults to 1.
      prefetch_count: 0                    # Prefetch message count per worker.
      queue:
        name: "upload-picture"
        options:
          durable: true
          args:
            "x-dead-letter-exchange": "fallback"
            "x-dead-letter-routing-key": "upload-picture"
        bindings:
          -
            routing_keys:
              - "android.#.upload"
              - "iphone.upload"
            exchange: upload-picture
      runner:
        type: command
        options:
          path: "testdata/receive.php"
```
